#!/usr/bin/env python3
"""Splits the car kit's wheels out of its bodies, so a vehicle can steer them.

The kit authors each car as a single mesh holding the groups `body`,
`wheel-front-left`, `wheel-front-right`, `wheel-back-left` and `wheel-back-right`.
That is fine for a parked car and useless for a driven one: a raycast vehicle has
to place each wheel where its suspension puts it, and spin and steer it there.

For every car this writes, beside the original:

    <name>-body.obj    the car without its wheels
    <name>-wheel.obj   one wheel, recentred on its own axle so it spins in place

and records every car's wheel anchors and radius, measured from the art rather
than typed in, into `vehicles.json`.

Idempotent and re-runnable: the outputs are rewritten from the originals each
time, and the originals are never touched.

    python GTAClone/tools/split_car_wheels.py GTAClone/assets/models/cars
"""

import json
import os
import sys

WHEEL_PREFIX = "wheel-"
BODY_SUFFIX = "-body.obj"
WHEEL_SUFFIX = "-wheel.obj"


def parse_obj(path):
    """Positions, uvs, normals and faces grouped by `g` name."""
    v, vt, vn = [], [], []
    groups, current = {}, None
    for line in open(path, errors="ignore"):
        parts = line.split()
        if not parts:
            continue
        tag = parts[0]
        if tag == "v":
            v.append(tuple(float(x) for x in parts[1:4]))
        elif tag == "vt":
            vt.append(tuple(float(x) for x in parts[1:3]))
        elif tag == "vn":
            vn.append(tuple(float(x) for x in parts[1:4]))
        elif tag == "g":
            current = parts[1] if len(parts) > 1 else ""
            groups.setdefault(current, [])
        elif tag == "f":
            # Triangulate as a fan; the kit is already triangles or quads.
            corners = [tuple((int(i) if i else 0) for i in (c.split("/") + ["", ""])[:3])
                       for c in parts[1:]]
            for k in range(1, len(corners) - 1):
                groups.setdefault(current, []).append(
                    (corners[0], corners[k], corners[k + 1]))
    return v, vt, vn, groups


def write_obj(path, v, vt, vn, faces, offset=(0.0, 0.0, 0.0), source=""):
    """Emit only the vertices the given faces use, renumbered from 1."""
    vmap, tmap, nmap = {}, {}, {}
    for tri in faces:
        for vi, ti, ni in tri:
            if vi and vi not in vmap:
                vmap[vi] = len(vmap) + 1
            if ti and ti not in tmap:
                tmap[ti] = len(tmap) + 1
            if ni and ni not in nmap:
                nmap[ni] = len(nmap) + 1

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by GTAClone/tools/split_car_wheels.py from %s\n" % source)
        f.write("# Kenney Car Kit (CC0 1.0); the split is a derivative work, also CC0.\n")
        f.write("mtllib colormap.mtl\n")
        for original in sorted(vmap, key=lambda i: vmap[i]):
            p = v[original - 1]
            f.write("v %.6f %.6f %.6f\n" % (p[0] - offset[0], p[1] - offset[1], p[2] - offset[2]))
        for original in sorted(tmap, key=lambda i: tmap[i]):
            f.write("vt %.6f %.6f\n" % vt[original - 1])
        for original in sorted(nmap, key=lambda i: nmap[i]):
            f.write("vn %.6f %.6f %.6f\n" % vn[original - 1])
        f.write("usemtl colormap\n")
        for tri in faces:
            out = []
            for vi, ti, ni in tri:
                out.append("%d/%s/%s" % (vmap[vi],
                                         tmap[ti] if ti else "",
                                         nmap[ni] if ni else ""))
            f.write("f %s\n" % " ".join(out))
    return len(vmap), len(faces)


def bounds_of(v, faces):
    used = {vi for tri in faces for vi, _, _ in tri}
    pts = [v[i - 1] for i in used]
    lo = [min(p[a] for p in pts) for a in range(3)]
    hi = [max(p[a] for p in pts) for a in range(3)]
    return lo, hi


def split(path):
    name = os.path.basename(path)[:-4]
    v, vt, vn, groups = parse_obj(path)
    wheels = {g: f for g, f in groups.items() if g.startswith(WHEEL_PREFIX) and f}
    if not wheels:
        return None
    body = [tri for g, f in groups.items() if not g.startswith(WHEEL_PREFIX) for tri in f]
    if not body:
        return None

    folder = os.path.dirname(path)
    write_obj(os.path.join(folder, name + BODY_SUFFIX), v, vt, vn, body, source=name + ".obj")

    anchors = {}
    for g, faces in wheels.items():
        lo, hi = bounds_of(v, faces)
        anchors[g] = [(lo[a] + hi[a]) / 2.0 for a in range(3)]

    # One wheel serves all four: they are mirror images, which a half turn about
    # Y reproduces. Recentred on its own axle so rotating the node spins it in
    # place instead of swinging it around the car.
    ref = ("wheel-front-left" if "wheel-front-left" in wheels
           else sorted(wheels)[0])
    lo, hi = bounds_of(v, wheels[ref])
    centre = [(lo[a] + hi[a]) / 2.0 for a in range(3)]
    write_obj(os.path.join(folder, name + WHEEL_SUFFIX), v, vt, vn, wheels[ref],
              offset=centre, source="%s.obj group %s" % (name, ref))

    blo, bhi = bounds_of(v, body)
    # The axle runs across the car, so the wheel's radius is half its larger
    # in-plane extent, not half its width.
    radius = max(hi[1] - lo[1], hi[2] - lo[2]) / 2.0
    return name, {
        "wheels": anchors,
        "wheelRadius": round(radius, 5),
        "wheelWidth": round(hi[0] - lo[0], 5),
        "bodyMin": [round(x, 5) for x in blo],
        "bodyMax": [round(x, 5) for x in bhi],
    }


def main(folder):
    out = {}
    for entry in sorted(os.listdir(folder)):
        if not entry.endswith(".obj"):
            continue
        if entry.endswith(BODY_SUFFIX) or entry.endswith(WHEEL_SUFFIX):
            continue          # never re-split our own output
        result = split(os.path.join(folder, entry))
        if result:
            out[result[0]] = result[1]

    manifest = os.path.join(folder, "vehicles.json")
    with open(manifest, "w", encoding="utf-8", newline="\n") as f:
        json.dump({"schema": 1, "vehicles": out}, f, indent=1, sort_keys=True)
        f.write("\n")
    print("split %d cars -> %s" % (len(out), manifest))
    for name in sorted(out)[:6]:
        d = out[name]
        print("  %-18s %d wheels  radius %.3f  width %.3f"
              % (name, len(d["wheels"]), d["wheelRadius"], d["wheelWidth"]))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else
         os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                      "assets", "models", "cars"))
