#pragma once

// CookedClip — compact runtime format for a compiled animation clip.
// Tracks are bound by bone index (no names), times are quantized to 16 bits
// per page, translations/scales to 16 bits per component with per-track
// bounds, rotations in 48-bit smallest-three. A constant channel stores only
// one key. This data is never edited: it lives in the derived cache and is
// regenerated by AnimationCooker.

#include "scene/animation/AnimationClip.hpp"
#include "scene/animation/Pose.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace saida {

// A page covers a contiguous time slice of the track: long sequences thus
// keep constant time precision, and the sampler never interpolates across a
// boundary (a page's first key duplicates the previous page's last one).
struct CookedPage {
    float startTime = 0.0f;
    float timeScale = 0.0f;  // seconds per quantized step (0 = single key)
    uint32_t firstKey = 0;
    uint32_t keyCount = 0;
};

struct CookedTrack {
    uint16_t boneIndex = 0;
    TrackTarget target = TrackTarget::Translation;
    TrackInterpolation interpolation = TrackInterpolation::Linear;
    uint32_t firstPage = 0;
    uint32_t pageCount = 0;
    // Dequantization bounds for vec3 tracks (ignored for rotation).
    glm::vec3 valueMin{0.0f};
    glm::vec3 valueScale{0.0f};
};

// Remembered read position of a track: forward playback resumes from the
// last key found (amortized O(1) cost), a seek falls back to binary search
// then repositions the cursor.
struct CookedCursor {
    uint32_t page = 0;
    uint32_t key = 0;
};

class CookedClip {
public:
    static constexpr uint32_t kMagic = 0x434E4153;  // "SANC"
    static constexpr uint32_t kVersion = 1;
    static constexpr uint32_t kValuesPerKey = 3;    // u16 per key (vec3 and quat)
    static constexpr float kTimeSteps = 65535.0f;   // quantization steps per page

    // Samples all tracks at `time` (seconds, clamped to the keys).
    // `outPose` must already contain the rest pose for absent channels.
    // `cursors` (array of trackCount() entries, optional) speeds up forward
    // playback — the caller owns its memory.
    void sample(float time, LocalPose& outPose, CookedCursor* cursors = nullptr) const;

    const std::string& name() const { return name_; }
    float duration() const { return duration_; }
    size_t trackCount() const { return tracks_.size(); }
    size_t keyCount() const { return times_.size(); }
    size_t pageCount() const { return pages_.size(); }
    size_t dataBytes() const;

    std::vector<uint8_t> serialize() const;
    static bool deserialize(const uint8_t* data, size_t size, CookedClip& out,
                            std::string* error = nullptr);

    // Smallest-three encoding: 3 x 15 bits of components + 2 bits for the
    // largest component's index, spread across three uint16s.
    static void quantizeRotation(const glm::quat& q, uint16_t out[3]);
    static glm::quat dequantizeRotation(const uint16_t in[3]);

private:
    friend class AnimationCooker;

    void sampleTrack(const CookedTrack& track, float time,
                     CookedCursor& cursor, Transform& out) const;
    float keyTime(const CookedPage& page, uint32_t key) const;
    glm::vec3 keyVec3(const CookedTrack& track, uint32_t key) const;
    glm::quat keyQuat(uint32_t key) const;

    std::string name_;
    float duration_ = 0.0f;
    std::vector<CookedTrack> tracks_;
    std::vector<CookedPage> pages_;
    std::vector<uint16_t> times_;   // 1 u16 per key, relative to its page
    std::vector<uint16_t> values_;  // kValuesPerKey u16 per key
};

} // namespace saida
